"""update feedback

Revision ID: 0033bb44ce36
Revises: 408e45e2fba8
Create Date: 2025-07-19 15:39:28.663632

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0033bb44ce36'
down_revision = '408e45e2fba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
