"""add_audit_log_tables

Revision ID: 2b7bbaf7e9b0
Revises: 88b5579c3e67
Create Date: 2025-08-09 09:16:48.899694

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "2b7bbaf7e9b0"
down_revision = "88b5579c3e67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "line_item_audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("line_item_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "old_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "new_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("old_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("old_tools", sa.JSON(), nullable=True),
        sa.Column("new_tools", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line_item_message_audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("line_item_message_id", sa.Integer(), nullable=False),
        sa.Column("line_item_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "old_role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "new_role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("old_content", sa.Text(), nullable=True),
        sa.Column("new_content", sa.Text(), nullable=True),
        sa.Column("old_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for better performance
    op.create_index(
        "idx_line_item_audit_line_item_id", "line_item_audit_log", ["line_item_id"]
    )
    op.create_index(
        "idx_line_item_audit_project_id", "line_item_audit_log", ["project_id"]
    )
    op.create_index("idx_line_item_audit_user_id", "line_item_audit_log", ["user_id"])
    op.create_index(
        "idx_line_item_audit_timestamp", "line_item_audit_log", ["timestamp"]
    )

    op.create_index(
        "idx_line_item_message_audit_message_id",
        "line_item_message_audit_log",
        ["line_item_message_id"],
    )
    op.create_index(
        "idx_line_item_message_audit_line_item_id",
        "line_item_message_audit_log",
        ["line_item_id"],
    )
    op.create_index(
        "idx_line_item_message_audit_project_id",
        "line_item_message_audit_log",
        ["project_id"],
    )
    op.create_index(
        "idx_line_item_message_audit_timestamp",
        "line_item_message_audit_log",
        ["timestamp"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index(
        "idx_line_item_message_audit_timestamp", "line_item_message_audit_log"
    )
    op.drop_index(
        "idx_line_item_message_audit_project_id", "line_item_message_audit_log"
    )
    op.drop_index(
        "idx_line_item_message_audit_line_item_id", "line_item_message_audit_log"
    )
    op.drop_index(
        "idx_line_item_message_audit_message_id", "line_item_message_audit_log"
    )

    op.drop_index("idx_line_item_audit_timestamp", "line_item_audit_log")
    op.drop_index("idx_line_item_audit_user_id", "line_item_audit_log")
    op.drop_index("idx_line_item_audit_project_id", "line_item_audit_log")
    op.drop_index("idx_line_item_audit_line_item_id", "line_item_audit_log")

    # Drop tables
    op.drop_table("line_item_message_audit_log")
    op.drop_table("line_item_audit_log")
    # ### end Alembic commands ###
