"""update line index for message


Revision ID: 408e45e2fba8
Revises: bffb961b3866
Create Date: 2025-07-19 15:27:10.289054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '408e45e2fba8'
down_revision = 'bffb961b3866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_message_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.drop_column('line_message_index')

    # ### end Alembic commands ###
