"""add_projects_table

Revision ID: 583d1ab44164
Revises: ad88134d00cc
Create Date: 2025-07-19 10:08:24.198386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '583d1ab44164'
down_revision = 'ad88134d00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
