"""update role.

Revision ID: 6c87e6663d73
Revises: 4cb4fba56379
Create Date: 2025-07-19 13:09:59.613962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c87e6663d73'
down_revision = '4cb4fba56379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER', 'SYSTEM'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item_message', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.ENUM('ADMIN', 'USER', 'SYSTEM'),
               nullable=True)

    # ### end Alembic commands ###
