"""initialize_integer_primary_keys

Revision ID: 93125e99b114
Revises: 1a31ce608336
Create Date: 2025-07-19 09:51:31.920245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93125e99b114'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('new_owner_id')
        batch_op.drop_column('new_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('new_owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
