"""update task_is

Revision ID: adb65ce6240c
Revises: 6c87e6663d73
Create Date: 2025-07-19 13:40:31.136889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adb65ce6240c'
down_revision = '6c87e6663d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
