"""add_foreign_keys_to_audit_tables

Revision ID: c439a4ed6cf0
Revises: 2b7bbaf7e9b0
Create Date: 2025-08-09 09:30:03.154144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c439a4ed6cf0'
down_revision = '2b7bbaf7e9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add foreign keys for line_item_audit_log
    with op.batch_alter_table('line_item_audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_line_item_audit_log_user_id', 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_line_item_audit_log_line_item_id', 'line_item', ['line_item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_line_item_audit_log_project_id', 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # Add foreign keys for line_item_message_audit_log
    with op.batch_alter_table('line_item_message_audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_line_item_message_audit_log_user_id', 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_line_item_message_audit_log_line_item_id', 'line_item', ['line_item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_line_item_message_audit_log_project_id', 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_line_item_message_audit_log_line_item_message_id', 'line_item_message', ['line_item_message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys for line_item_message_audit_log
    with op.batch_alter_table('line_item_message_audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_line_item_message_audit_log_line_item_message_id', type_='foreignkey')
        batch_op.drop_constraint('fk_line_item_message_audit_log_project_id', type_='foreignkey')
        batch_op.drop_constraint('fk_line_item_message_audit_log_line_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_line_item_message_audit_log_user_id', type_='foreignkey')

    # Drop foreign keys for line_item_audit_log
    with op.batch_alter_table('line_item_audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_line_item_audit_log_project_id', type_='foreignkey')
        batch_op.drop_constraint('fk_line_item_audit_log_line_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_line_item_audit_log_user_id', type_='foreignkey')

    # ### end Alembic commands ###
