"""update line item to load message

Revision ID: c57f992c455f
Revises: 0033bb44ce36
Create Date: 2025-07-19 15:47:31.016702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c57f992c455f'
down_revision = '0033bb44ce36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
