"""add line items.

Revision ID: d06407416305
Revises: 69accce0f83b
Create Date: 2025-07-19 12:40:48.543288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd06407416305'
down_revision = '69accce0f83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_item_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'SYSTEM', name='role'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item_message')
    op.drop_table('line_item')
    # ### end Alembic commands ###
