"""add status for line item


Revision ID: e968105aceb4
Revises: c57f992c455f
Create Date: 2025-07-19 17:00:03.213591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e968105aceb4'
down_revision = 'c57f992c455f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('UNLABELED', 'CONFIRMED', 'APPROVED', 'REJECTED', name='lineitemstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
